config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :contacts
  resources :companies
  resources :users
  resources :time_trackings

  root 'companies#index'

  get 'facebook' => 'facebook#index'
  get 'twitter' => 'twitter#index'
  get 'google_analytics' => 'google_analytics#index'
  get 'linkedin' => 'linkedin#index'
  get 'instagram' => 'instagram#index'

  get 'facebook/login'
  get 'facebook/logout'
  get 'facebook/callback'
  get 'facebook/login_page'
  post 'facebook/report'
  get 'facebook/fresh_up_data'
  get 'facebook/options'
  get 'facebook/update_id'

  get 'twitter/login_page'
  get 'auth/twitter/callback' => 'twitter#callback'
  get 'twitter/logout'

  get 'linkedin/login_page'
  get 'auth/linkedin/callback' => 'linkedin#callback'
  get 'linkedin/logout'
  get 'linkedin/options'
  post 'linkedin/report'
  get 'linkedin/update_id'

  get 'instagram/login_page'
  get 'instagram/callback'
  get 'instagram/logout'
  get 'instagram/login'

  get 'google_analytics/login_page'
  get 'auth/google_oauth2/callback' => 'google_analytics#callback'
  get 'google_analytics/logout'
  get 'google_analytics/adwords'
  post 'google_analytics/report'
  post 'google_analytics/adwords_report'
  get 'google_analytics/options'
  get 'google_analytics/update_adwords_id'
  get 'google_analytics/update_analytics_id'

  get 'login' => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  get 'companies_calendar' => 'companies#calendar'
  get 'client_information' => 'companies#client_information'
  get 'client_contacts' => 'companies#client_contacts'
  get 'content_distribution' => 'companies#content_distribution'
  get 'create_post_report' => 'companies#create_post_report'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  has_one :social_id, dependent: :destroy
  has_many :time_trackings, dependent: :destroy
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :status, presence: true # status maps 1: active, 2: pipeline, 3: lost, 4: completed
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:destroy]

  # GET /companies
  # GET /companies.json
  def index
    if params[:status]
      @status = params[:status]
    else
      @status = 2
    end

    @companies = Company.where(status: @status)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    remember_company @company
    @time_trackings = @company.time_trackings.where("date >= ?", Date.today.beginning_of_month).where("date <= ?", Date.today.end_of_month)
  end

  # shows the calendar of the client with the planned posts
  def calendar
    @start_date = nil
    @start_date = params["start_date"] if params["start_date"]
    @company = current_company
  end

  # shows the information about the client
  def client_information
    @company = current_company
  end

  # shows all contacts of the client
  def client_contacts
    @company = current_company
  end

  # shows a pie chart for the distribution of the planned posts
  def content_distribution
    @posts = current_company.posts.where("start_time >= ?", Date.today.beginning_of_month).where("start_time <= ?", Date.today.end_of_month)
  end

  # create report of all planned posts for the date in the params
  def create_post_report
    @company = current_company

    # create a report with a start_date or with the date of today for the whole month
    if params["start_date"]
      @calendar_date = Date.parse(params["start_date"])
    else
      @calendar_date = Date.today
    end

    @posts = @company.posts.where("start_time >= ?", @calendar_date.beginning_of_month).where("start_time <= ?", @calendar_date.end_of_month)
    print "Posts: " + @posts.to_s
    respond_to do |format|
      format.pdf do
        render  pdf: 'report',
                layout: 'layouts/pdf.html',
                template: 'companies/posts.pdf.erb',
                encoding: "UTF-8",
                :margin => {:top                => 15,
                            :bottom             => 10,
                            :left               => 20,
                            :right              => 20},
                :footer => {
                  :content => render_to_string(:template => 'layouts/footer.pdf.erb')
                }
      end
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
    respond_to do |format|
      format.html # new.html.erb
      format.js # new.js.erb
    end
  end

  # GET /companies/1/edit
  def edit
    respond_to do |format|
      format.html # edit.html.erb
      format.js # edit.js.erb
    end
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.create_social_id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        remember_company(@company)
        format.html { redirect_to "/client_information", notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    destroy_facebook_insights
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # destroy collections of facebook insights
    def destroy_facebook_insights
      name = @company.name.split.join
      FacebookInsights.destroy_collection(name)
      FacebookInsights.destroy_collection(name.to_s + "_posts")
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description, :lead_source, :job_types, :website,
                                      :monthly_total, :address, :status, :total_hours, :one_time_cost,
                                      :facebook, :twitter, :linkedin, :instagram, :notes)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  # sum up the total revenue of all companies
  def sum_up_monthly_total(values)
    sum = 0
    values.each { |v|
      sum = sum + v.monthly_total.to_i
    }
    sum
  end

  # sum up the one time cost of all companies
  def sum_up_one_time_cost(values)
    sum = 0
    values.each { |v|
      sum = sum + v.one_time_cost.to_i
    }
    sum
  end

  # calculate the total amount money used with the spent time
  def sum_up_total_value_of_time_trackings(values)
    sum = 0
    values.each { |v|
      sum = sum + v.spent_time * v.hourly_rate
    }
    sum
  end

  # format data to display it in a pie chart (hours of time trackings)
  def sum_up_total_hours_to_display(values, total)
    return {} if total.blank?
    hours = {}
    sum = 0

    values.each { |v|
      sum = sum + v.spent_time
    }
    left = total - sum
    left = 0 if left < 0

    # save it in hash for chartkick
    hours[:spent] = sum
    hours[:left] = left
    hours
  end

  # format data to display it in a pie chart (money)
  def get_total_values_to_display(values, total)
    return {} if total.blank?
    sum = sum_up_total_value_of_time_trackings(values)
    money = {}
    left = total - sum
    left = 0 if left < 0

    # save it in hash for chartkick
    money[:used] = sum
    money[:left] = left
    money
  end

  # sum up the time of every single employee to create a chart
  def get_spent_time_of_employees(values)
    return {} if values.nil?
    employees = Hash.new(0)
    values.each { |v|
      employees[v.user.name] = employees[v.user.name] + v.spent_time
    }
    employees
  end

  # check for which month the post report should be created
  def get_month_for_posts_report(start_date)
    if start_date.blank?
      "create_post_report.pdf"
    else
      "create_post_report.pdf?start_date=" + start_date.to_s
    end
  end

  # for creating header in the post pdf report. get name of month.
  def get_month(start_date)
    if start_date.blank?
      Date.today.strftime("%B")
    else
      start_date.strftime("%B")
    end
  end

  # get the headline of the dashboard, depends on the status
  def get_header(status)
    if status == "1"
      "Active Clients"
    elsif status == "2"
      "Pipeline"
    elsif status == "3"
      "Lost Clients"
    elsif status == "4"
      "Completed"
    else
      "Dashboard"
    end
  end

  # status collection for the collection_select tag
  def get_status_collection
    status_hash = [
      [1, 'Active'],
      [2, 'Pipeline'],
      [3, 'Lost'],
      [4, 'Completed']
    ]
  end

  # maps the status to the name
  def get_name_of_status(status)
    if status == 1 || status == "1"
      "Active"
    elsif status == 2 || status == "2"
      "Pipeline"
    elsif status == 3 || status == "3"
      "Lost"
    elsif status == 4 || status == "4"
      "Completed"
    else
      ""
    end
  end

  # get title of the income, different for each dashboard
  def get_name_of_income(status)
    if status == "2" || status == 2
      "Predicted "
    elsif status == "3" || status == 3
      "Lost "
    else
      "Monthly "
    end
  end

  # add a http protocol to the url if there is no protocol
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>

  <% if @company.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <strong><%= pluralize(@company.errors.count, "error") %>
      prohibited this company from being saved:</strong>

    <ul>
      <% @company.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :lead_source %>
    <%= f.text_field :lead_source, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :job_types %>
    <%= f.text_field :job_types, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :monthly_total %>
    <%= f.number_field :monthly_total, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :one_time_cost %>
    <%= f.number_field :one_time_cost, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :total_hours %>
    <%= f.text_field :total_hours, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :status %>
    <%= f.collection_select :status, get_status_collection, :first, :last, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :facebook %>
    <%= f.text_field :facebook, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :twitter %>
    <%= f.text_field :twitter, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :linkedin %>
    <%= f.text_field :linkedin, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :instagram %>
    <%= f.text_field :instagram, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <br>
  <div class="form-inline">
    <%= f.submit class: "btn btn-primary btn-block"%>
  </div>

<% end %>

app/views/companies/calendar.html.erb
<div class="col-sm-2">
  <%= render 'layouts/sidebar' %>
</div>
<div class="col-sm-10">
  <div class="row">
    <div class="container-fluid">
      <%= month_calendar events: @company.posts do |date, posts| %>
        <%= content_tag :div, class: "calendar-day", style: "height:inherit;", data: {date: date} do %>
          <div class="navbar-right container-fluid">
            <%= date.day %>
          </div>
          <% posts.each do |post| %>
            <%= content_tag :span, class: "insideLink", style: "cursor:pointer;", data: {number: post.id} do %>
              <%= get_all_post_types[post.post_type].html_safe %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <div class="text-right">
        <div class="btn-group">
          <%= link_to "New Post", new_post_path, class: "btn btn-primary", remote: true %>
          <%= link_to "Create Report", get_month_for_posts_report(@start_date), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/client_contacts.html.erb
<div class="col-sm-2">
  <%= render 'layouts/sidebar' %>
</div>
<div class="col-sm-10">
  <div class="row">
    <div class="col-sm-6">
      <h3>Contacts</h3>
    </div>
    <div class="col-sm-6 text-right">
      <%= link_to 'Add Contact', new_contact_path, class: "btn btn-primary", style: "margin-top:15px;", remote: true %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Phone</th>
        <th>Mobile</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @company.contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.mobile %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact), remote: true %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/companies/client_information.html.erb
<div class="col-sm-2">
  <%= render 'layouts/sidebar' %>
</div>
<div class="col-sm-10">
  <div class="information">
    <div class="row">
      <div class="col-sm-6">
        <h1><%= @company.name %></h1>
      </div>
      <div class="col-sm-6 text-right">
        <h1>
          Total hours:
          <%= @company.total_hours %>
        </h1>
      </div>
    </div>

    <div class="row well well-white">
      <h4>Job Information</h4>
      <div class="col-sm-4">
        <strong>Status:</strong>
        <%= get_name_of_status @company.status %>
      </div>
      <div class="col-sm-4">
        <strong>Lead source:</strong>
        <%= @company.lead_source %>
      </div>
      <div class="col-sm-4">
        <strong>Job types:</strong>
        <%= @company.job_types %>
      </div>
    </div>

    <div class="row well well-white">
      <h4>Income</h4>
      <div class="col-sm-4">
        <strong>Monthly total:</strong>
        $<%= @company.monthly_total.to_i %>
      </div>
      <div class="col-sm-4">
        <strong>One time cost:</strong>
        $<%= @company.one_time_cost.to_i %>
      </div>
      <div class="col-sm-4">
        <strong>Annual revenue:</strong>
        $<%= @company.monthly_total.to_i * 12 + @company.one_time_cost.to_i %>
      </div>
    </div>

    <div class="row well well-white">
      <h4>Company Information</h4>
      <div class="col-sm-4">
        <strong>Address:</strong>
        <%= @company.address %>
      </div>
      <div class="col-sm-4">
        <strong>Website:</strong>
        <%= link_to @company.website, url_with_protocol(@company.website), target: 'blank' %>
      </div>
      <div class="col-sm-4">
        <strong>Description:</strong>
        <div>
          <%= @company.description %>
        </div>
      </div>
      <br style="clear:both;">
      <hr style="background-color:#f1f1f1;display:block;">
      <div>
        <strong>Notes:</strong>
        <div>
          <%= @company.notes %>
        </div>
      </div>
    </div>

    <div class="row well well-white">
      <h4>Social Media</h4>
      <br>
      <% if !@company.facebook.blank? %>
        <div class="col-xs-3 text-center">
          <%= link_to('<i class="fa fa-fw fa-facebook fa-3x"></i>'.html_safe, url_with_protocol(@company.facebook), target: "_blank") %>
        </div>
      <% end %>
      <% if !@company.twitter.blank? %>
        <div class="col-xs-3 text-center">
          <%= link_to('<i class="fa fa-fw fa-twitter fa-3x"></i>'.html_safe, url_with_protocol(@company.twitter), target: "_blank") %>
        </div>
      <% end %>
      <% if !@company.linkedin.blank? %>
        <div class="col-xs-3 text-center">
          <%= link_to('<i class="fa fa-fw fa-linkedin fa-3x"></i>'.html_safe, url_with_protocol(@company.linkedin), target: "_blank") %>
        </div>
      <% end %>
      <% if !@company.instagram.blank? %>
        <div class="col-xs-3 text-center">
          <%= link_to('<i class="fa fa-fw fa-instagram fa-3x"></i>'.html_safe, url_with_protocol(@company.instagram), target: "_blank") %>
        </div>
      <% end %>
    </div>

    <div class="text-right">
      <div class="btn-group">
        <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-primary", remote: true %>
        <%= link_to 'Delete', @company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/companies/content_distribution.html.erb
<div class="col-sm-2">
  <%= render 'layouts/sidebar' %>
</div>
<div class="col-sm-10">
  <h3>Content Distribution</h3>
  <%= pie_chart @posts.group(:post_type).count %>
</div>

app/views/companies/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Editing Company</h1>

  <%= render 'form' %>

  <%= link_to 'Back', @company %>
</div>

app/views/companies/edit.js.erb
$modal = $('.modal'),
$modalBody = $('.modal .modal-body'),
$modalHeading = $('.modal .modal-heading');
$modalHeading.html("Edit Company");
$modalBody.html("<%= escape_javascript(render 'form') %>");
$modal.modal();

app/views/companies/index.html.erb
<div class="col-sm-2">
  <%= render 'layouts/sidebar_dashboard' %>
</div>
<div class="col-sm-10">
  <div class="row">
    <div class="col-sm-6">
      <%= link_to 'New Client', new_company_path, class: "btn btn-primary", style: "margin-top:15px", remote: true %>
    </div>
    <div class="col-sm-6 text-right">
      <%= ('<h3>Total ' + get_name_of_status(@status) + ': $' + sum_up_monthly_total(@companies).to_s + '</h3>').html_safe %>
    </div>
  </div>
  <div class="row container-fluid">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Lead Source</th>
          <th>Job Types</th>
          <th>Website</th>
          <th>Monthly Total</th>
          <th>One Time Cost</th>
          <th>Annual Value</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.lead_source %></td>
          <td><%= company.job_types %></td>
          <td><%= link_to company.website, url_with_protocol(company.website), target: 'blank' %></td>
          <td>$<%= company.monthly_total.to_i %></td>
          <td>$<%= company.one_time_cost.to_i %></td>
          <td>$<%= company.monthly_total.to_i * 12 + company.one_time_cost.to_i %></td>
          <td><%= link_to 'Show', company %></td>
          <td><%= link_to 'Edit', edit_company_path(company), remote: true %></td>
          <% if current_user.admin? %>
          <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <hr>
  <div class="row vertical-align">
    <div class="col-sm-7">
      <div class="col-sm-6">
        <h3>Lead Sources</h3>
        <%= pie_chart @companies.group(:lead_source).count %>
      </div>
      <div class="col-sm-6">
        <h3>Job Types</h3>
        <%= pie_chart @companies.group(:job_types).count %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="col-xs-7">
        <%= ('<h3>Monthly Income: </h3>').html_safe %>
        <%= ('<h3>Annual Income: </h3>').html_safe %>
      </div>
      <div class="col-xs-5 text-right">
        <%= ('<h3>$' + sum_up_monthly_total(@companies).to_s + '</h3>').html_safe %>
        <%= ('<h3>$' + (sum_up_monthly_total(@companies) * 12 + sum_up_one_time_cost(@companies)).to_s + '</h3>').html_safe %>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/companies/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New Company</h1>

  <%= render 'form' %>

  <%= link_to 'Back', companies_path %>
</div>

app/views/companies/new.js.erb
$modal = $('.modal'),
$modalBody = $('.modal .modal-body'),
$modalHeading = $('.modal .modal-heading');
$modalHeading.html("New Company");
$modalBody.html("<%= escape_javascript(render 'form') %>");
$modal.modal();

app/views/companies/posts.pdf.erb
<h3>Posts for <%= get_month(@calendar_date) %></h3>

<table class="table table-striped table-condensed">
  <tr>
    <th>Type</th>
    <th>Title</th>
    <th>Date</th>
  </tr>
  <% @posts.each do |post| %>
  <tr>
    <td><%= get_all_post_types[post.post_type].html_safe %><%= post.post_type %></td>
    <td><%= post.title %></td>
    <td><%= post.start_time.strftime("%d/%m/%Y") %></td>
  </tr>
  <% end %>
</table>

app/views/companies/show.html.erb
<div class="col-sm-2">
  <%= render 'layouts/sidebar' %>
</div>
<div class="col-sm-10">
  <div class="row">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <h3>Time Trackings</h3>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'Add Time', new_time_tracking_path, class: "btn btn-primary", style: "margin-top:15px;", remote: true %>
        </div>
      </div>
      <h4>Total Value:
        <%= sum_up_total_value_of_time_trackings(@time_trackings) %>$</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Spent Time (hours)</th>
            <th>Hourly Rate</th>
            <th>Date</th>
            <th>Total Value</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @time_trackings.each do |time_tracking| %>
          <tr>
            <td><%= link_to time_tracking.user.name, time_tracking.user, remote: true %></td>
            <td><%= time_tracking.spent_time %>h</td>
            <td><%= time_tracking.hourly_rate %>$</td>
            <td><%= time_tracking.date.strftime('%d/%m/%Y') %></td>
            <td><%= time_tracking.spent_time * time_tracking.hourly_rate %>$</td>
            <td><%= link_to 'Show', time_tracking, remote: true %></td>
            <% if current_user.admin? || current_user?(time_tracking.user) %>
            <td><%= link_to 'Edit', edit_time_tracking_path(time_tracking), remote: true %></td>
          <% else %>
            <td></td>
            <% end %>
            <% if current_user.admin? %>
            <td><%= link_to('Delete', time_tracking, method: :delete, data: { confirm: 'Are you sure?' }) %></td>
            <% elsif current_user.admin? %>
            <td></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <% if @company.total_hours %>
    <div class="col-sm-4">
      <h3>Time</h3>
      <%= pie_chart sum_up_total_hours_to_display(@time_trackings, @company.total_hours) %>
    </div>
    <% end %>
    <% if @company.monthly_total %>
    <div class="col-sm-4">
      <h3>Income</h3>
      <%= pie_chart get_total_values_to_display(@time_trackings, @company.monthly_total) %>
    </div>
    <% end %>
    <% if @time_trackings.count > 0 %>
    <div class="col-sm-4">
      <h3>Employees</h3>
      <%= column_chart get_spent_time_of_employees(@time_trackings) %>
    </div>
    <% end %>
  </div>
</div>

<br>