config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :contacts
  resources :companies
  resources :users
  resources :time_trackings

  root 'companies#index'

  get 'facebook' => 'facebook#index'
  get 'twitter' => 'twitter#index'
  get 'google_analytics' => 'google_analytics#index'
  get 'linkedin' => 'linkedin#index'
  get 'instagram' => 'instagram#index'

  get 'facebook/login'
  get 'facebook/logout'
  get 'facebook/callback'
  get 'facebook/login_page'
  post 'facebook/report'
  get 'facebook/fresh_up_data'
  get 'facebook/options'
  get 'facebook/update_id'

  get 'twitter/login_page'
  get 'auth/twitter/callback' => 'twitter#callback'
  get 'twitter/logout'

  get 'linkedin/login_page'
  get 'auth/linkedin/callback' => 'linkedin#callback'
  get 'linkedin/logout'
  get 'linkedin/options'
  post 'linkedin/report'
  get 'linkedin/update_id'

  get 'instagram/login_page'
  get 'instagram/callback'
  get 'instagram/logout'
  get 'instagram/login'

  get 'google_analytics/login_page'
  get 'auth/google_oauth2/callback' => 'google_analytics#callback'
  get 'google_analytics/logout'
  get 'google_analytics/adwords'
  post 'google_analytics/report'
  post 'google_analytics/adwords_report'
  get 'google_analytics/options'
  get 'google_analytics/update_adwords_id'
  get 'google_analytics/update_analytics_id'

  get 'login' => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  get 'companies_calendar' => 'companies#calendar'
  get 'client_information' => 'companies#client_information'
  get 'client_contacts' => 'companies#client_contacts'
  get 'content_distribution' => 'companies#content_distribution'
  get 'create_post_report' => 'companies#create_post_report'
end

app/views/layouts/_header.html.erb
<div id="header-bar" class="container-fluid row">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <%= image_tag "logo-trans-white01.png", height: "30", class: "navbar-logo" %>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Menu
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to '<i class="fa fa-fw fa-home"></i> Dashboard'.html_safe, companies_path %></li>
            <li class="divider"></li>
            <li><%= link_to '<i class="fa fa-fw fa-users"></i> Users'.html_safe, users_path %></li>
            <li><%= link_to '<i class="fa fa-fw fa-phone"></i> Contacts'.html_safe, contacts_path %></li>
            <li><%= link_to '<i class="fa fa-fw fa-clock-o"></i> Time Trackings'.html_safe, time_trackings_path %></li>
            <li><%= link_to '<i class="fa fa-fw fa-calendar"></i> Calendar'.html_safe, posts_path %></li>
            <li class="divider"></li>
            <li><%= link_to '<i class="fa fa-fw fa-sign-out"></i>Logout'.html_safe, logout_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
  <br><br><br>
</div>

app/views/layouts/_modal.html.erb
<div class="modal fade" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-heading">Modal header</h3>
      </div>
      <div class="modal-body">
        <p>One fine body…</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidenav row content">
  <nav class="navbar sidebar-nav">
    <h4 id="company-name"><%= current_company.name  %></h4>
    <div id="collapse-group">
      <ul class="nav nav-pills nav-stacked">
        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-campaign">
            <i class="fa fa-fw fa-tasks"></i> Campaign
          </a>
        </li>
        <div id="collapse-campaign" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a href="/client_information"><i class="fa fa-fw fa-info"></i> Client Information</a>
          </li>
          <li>
            <a href="/client_contacts"><i class="fa fa-fw fa-phone"></i> Contacts</a>
          </li>
          <li>
            <%= link_to '<i class="fa fa-fw fa-clock-o"></i> Time Trackings'.html_safe, current_company %>
          </li>
          <li class="divider-blue"></li>
        </div>
        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-analytics">
            <i class="fa fa-fw fa-area-chart"></i> Analytics
          </a>
        </li>
        <div id="collapse-analytics" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a href="/google_analytics"><i class="fa fa-fw fa-google"></i> Google Analytics</a>
          </li>
          <li class="divider-blue"></li>
        </div>
        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-ppc">
            <i class="fa fa-fw fa-briefcase"></i> SEM</a>
        </li>
        <div id="collapse-ppc" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a href="/google_analytics/adwords"><i class="fa fa-fw fa-google"></i> Google AdWords</a>
          </li>
          <li class="divider-blue"></li>
        </div>

        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-seo">
            <i class="fa fa-fw fa-line-chart"></i> SEO</a>
        </li>
        <div id="collapse-seo" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a href="#site-auditor">Site Auditor</a>
          </li>
          <li>
            <a href="#rankings">Rankings</a>
          </li>
          <li class="divider-blue"></li>
        </div>

        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-social">
            <i class="fa fa-fw fa-comments"></i> Social
          </a>
        </li>
        <div id="collapse-social" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a href="/twitter"><i class="fa fa-fw fa-twitter"></i> Twitter</a>
          </li>
          <li>
            <a href="/facebook"><i class="fa fa-fw fa-facebook-official"></i> Facebook</a>
          </li>
          <li>
            <a href="/instagram"><i class="fa fa-fw fa-instagram"></i> Instagram</a>
          </li>
          <li>
            <a href="/linkedin"><i class="fa fa-fw fa-linkedin-square"></i> LinkedIn</a>
          </li>
          <li class="divider-blue"></li>
        </div>

        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-content">
            <i class="fa fa-fw fa-list-alt"></i> Content</a>
        </li>
        <div id="collapse-content" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a href="/companies_calendar"><i class="fa fa-fw fa-calendar"></i> Calendar</a>
          </li>
          <li>
            <a href="/content_distribution"><i class="fa fa-fw fa-pie-chart"></i> Content Distribution</a>
          </li>
          <li class="divider-blue"></li>
        </div>

        <li>
          <a class="collapse-close" data-toggle="collapse" data-target="#collapse-report">
            <span class="glyphicon glyphicon-file"></span> Report
          </a>
        </li>
        <div id="collapse-report" class="collapse nav nav-pills nav-stacked">
          <li class="divider-blue"></li>
          <li>
            <a id="create-report">
              <i class="fa fa-fw fa-print"></i>
              Create Report</a>
          </li>
          <li class="divider-blue"></li>
        </div>
      </ul>
    </div>
    <br>
  </nav>
</div>

app/views/layouts/_sidebar_dashboard.html.erb
<div class="sidenav row content">
  <nav class="navbar sidebar-nav">
    <div id="collapse-group">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to '<i class="fa fa-fw fa-meh-o"></i> Pipeline'.html_safe, companies_path(status: 2) %></li>
        <li><%= link_to '<i class="fa fa-fw fa-smile-o"></i> Clients'.html_safe, companies_path(status: 1) %></li>
        <li><%= link_to '<i class="fa fa-fw fa-frown-o"></i> Lost Clients'.html_safe, companies_path(status: 3) %></li>
        <li><%= link_to '<i class="fa fa-fw fa-check-circle"></i> Completed'.html_safe, companies_path(status: 4) %></li>
      </ul>
    </div>
    <br>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocketshp Reporter</title>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if logged_in? %>
    <%= render 'layouts/header' %>
    <% end %>
    <div class="container-fluid">

      <% if notice %>
      <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= notice %></p>
      </div>
      <% end %>

      <%= yield %>
    </div>
    <%= render "layouts/modal" %>
    <br><br>
    <script>
    $(document).on('page:change', init())
    </script>
  </body>
</html>

app/views/layouts/footer.pdf.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <%= wicked_pdf_javascript_include_tag "application" %>
    <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
    <script>
      function number_pages() {
        var vars = {};
        var x = document.location.search.substring(1).split('&');
        for (var i in x) {
          var z = x[i].split('=', 2);
          vars[z[0]] = unescape(z[1]);
        }
        var x = [
          'frompage',
          'topage',
          'page',
          'webpage',
          'section',
          'subsection',
          'subsubsection'
        ];
        for (var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for (var j = 0; j < y.length; ++j)
            y[j].textContent = vars[x[i]];
          }
        }
    </script>

  </head>
  <body onload="number_pages()">
    <div id="pdf-footer">
      <span class="page"></span>
      of
      <span class="topage"></span>
    </div>
  </body>

</html>

app/views/layouts/pdf.html.erb
<html>
  <head>
    <title>Report</title>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css", media: "all", "data-turbolinks-track" => true %>
    <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
    <%= wicked_pdf_javascript_include_tag "application" %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>